### ISSUE TITLE
missing class error following installation of theme

### ISSUE THREAD

**Issue by c-nv-s** [initbizlab/oc-cumulusdemo-plugin#3]
From following the demo installation instructions here https://docs.init.biz/cumulusdemo/

I receive the following error after running php artisan cumulus:seed
   
In Seed.php line 60:                                                                  
Class 'Initbiz\CumulusCore\Repositories\PlanRepository' not found  

I had to restore the following files on oc-cumuluscore-plugin branch c4a45ac38e for it to work:

plugins/initbiz/cumuluscore/contracts/ClusterInterface.php
plugins/initbiz/cumuluscore/contracts/PlanInterface.php
plugins/initbiz/cumuluscore/contracts/RepositoryInterface.php
plugins/initbiz/cumuluscore/contracts/UserInterface.php
plugins/initbiz/cumuluscore/repositories/ClusterRepository.php
plugins/initbiz/cumuluscore/repositories/PlanRepository.php
plugins/initbiz/cumuluscore/repositories/UserRepository.php

Steps to reproduce problem:
1. install october or use existing installation
2. install the cumulus theme
3. run php artisan cumulus:seed

**Comment by tomaszstrojny** [comment]
Hi,

Thanks for your interest in our plugins and sorry for the inconvenience.

Recently we have decided to remove the Cumulus Demo plugin and Cumulus Demo theme from the marketplace as they were hard to maintain and not so useful for the user. I will make them inactive right now. To see how Cumulus works you can visit our demo app at:

https://cumulus.init.biz/ and

https://cumulus.init.biz/backend (demo: demo).

Best regards,

Tomasz Strojny
